### ISSUE TITLE
Missing markdown hover language

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/lsif-semanticdb#13]
As lsif-semanticdb is now being used beyond just Scala, we can't hardcode for it anymore. I'm not sure if `metacp` attaches `Langauge` to `SymbolInformation`, but we currently don't do that in `semanticdb-javac`, hence we get the unknown language for markdown hovers [here](https://github.com/sourcegraph/lsif-semanticdb/blob/master/internal/index/indexer.go#L319-L322). 

We can't simply use the document language in the long term, as a symbol may be an external symbol defined in a different language to the document its referenced in. While it isnt _currently_ the case that external 3rd party symbols are included in the output (an amount of work will be involved for this if we assume deps may be not just java), it will be soon:tm:.

cc @olafurpg

**Comment by olafurpg** [comment]
You can safely assume that the `SymbolInformation` language matches the `TextDocument` language. This wasn't the case in semanticdb-scalac at one point when we emitted `SymbolInformation` for referenced symbols but now we only emit `SymbolInformation` for symbols that are defined within the `TextDocument`.

**Comment by Strum355** [comment]
> but now we only emit SymbolInformation for symbols that are defined within the TextDocument.

What was the reasons behind this? Was it to avoid having a lot of duplicated data across all semanticdb files for a project or another reason? 

> You can safely assume that the SymbolInformation language matches the TextDocument language. 

Once it becomes the case that we include `SymbolInformation` for external symbols, which we will need to do to include hover info for external symbols (see erics quote below), this mightnt be a 100% safe assumption (use of a Scala/Kotlin/Groovy library in a Java repo for example). 

Quote from @efritz "Hovers should be answered within the dump if possible. It would be more expensive to always rely on the xrepo lookup (if it’s indexed at all)"

With that in mind, what course of action can be taken for:
1. emitting hovers for external symbols in java projects (duplicating the work due to semanticdb-javac not having a 'global view' only 'translation-unit view' may add a significant extra cost, can it be done outside semanticdb-javac?)
2. supporting non-java external dependencies? (scala/kotlin/groovy, what additional complexity does that add to the indexers to detect and parse for the correct language?)
3. Also emitting hovers for external symbols from scala (so scala users don't just have hovers for project-local symbols)

I understand this is potentially a lot of big thinking, so we could always split these into different discussion streams (see: issues) :smile:

**Comment by olafurpg** [comment]
> What was the reasons behind this? Was it to avoid having a lot of duplicated data across all semanticdb files for a project or another reason?

Performance is one reason. In the case of docstrings, you don't have access to them for externally defined symbols. You only have the signature from the classpath.

> Once it becomes the case that we include SymbolInformation for external symbols, which we will need to do to include hover info for external symbols (see erics quote below), this mightnt be a 100% safe assumption (use of a Scala/Kotlin/Groovy library in a Java repo for example).

The assumption will remain safe. We will still emit `TextDocument` for external library sources. It's totally possible to generate external hovers within the repo by indexing the `*-sources.jar` of the external dependencies.

> supporting non-java external dependencies? (scala/kotlin/groovy, what additional complexity does that add to the indexers to detect and parse for the correct language?)

We can run the Scala/Kotlin indexers against `*-sources.jar` files.

**Comment by Strum355** [comment]
Just double checked with eric on if the behaviour on upload would make this work, and it does :smile: "everything is canonicalized before pruning, so any reachable hover for a range is re-attached directly to that range (essentially getting rid of result sets), then we throw out all ranges for unknown documents".

Looking at some semanticdb output, Im assuming the mapping is done based on the `symbol` string e.g. `org/springframework/boot/SpringApplication#`.

Your approaches seem technically sound then, and we can tackle them in the coming weeks :+1: cool stuff :partyparrot:

**Comment by scalabilitysolved** [comment]
@Strum355 as the associated PR has been merged is this issue suitable to be closed now?

**Comment by Strum355** [comment]
@scalabilitysolved yep this could be closed 🙂
